name: itmo-devops-sem1-project

services:
  server:
    extends:
      file: docker-compose.yml
      service: server
    image: itmo508541/itmo-devops-sem1-project:latest
    build: !reset null # https://stackoverflow.com/a/76913131
  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

volumes:
    database:
